name: Pipeline de Qualité
on: 
  push:
  workflow_dispatch: # Permet le lancement manuel 🖱️

jobs:
  pipeline-devops:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code 📥
        uses: actions/checkout@v3

      - name: Installation de Node.js 🟢
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Installation des dépendances 📦
        run: npm install --legacy-peer-deps

      - name: Vérification de la qualité (Linter) 🧹
        # On tente de lancer eslint sur le dossier src
        run: npx eslint src --ext .ts

        env:
          ESLINT_USE_FLAT_CONFIG: false
        # Si eslint échoue, on affiche un message d'erreur
        continue-on-error: false

      - name: Exécution des tests unitaires 🧪
        run: npm test
        # Si les tests échouent, on affiche un message d'erreur
        continue-on-error: false

      - name: Build du projet 🏗️
        run: npm run build
        # Si le build échoue, on affiche un message d'erreur
        continue-on-error: false

      - name: Analyse de la couverture de code 📊  
        run: npm run coverage
        # Si l'analyse échoue, on affiche un message d'erreur
        continue-on-error: false